# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-11-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_addr', models.EmailField(max_length=254)),
                ('meeting_link', models.URLField()),
                ('courses', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
    ]
