# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-11-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_num', models.IntegerField()),
                ('student_num', models.IntegerField()),
                ('sched_time', models.DateTimeField()),
                ('meeting_link', models.URLField()),
            ],
        ),
    ]
